go(john,bedroom,1).
go(sandra,kitchen,1).
go(mary,hallway,1).
get(john,football,1).
go(john,hallway,2).
drop(john,football,2).
go(mary,garden,2).
go(john,kitchen,3).
go(sandra,hallway,2).
go(daniel,hallway,1).
drop(mary,milk,2).
go(mary,bathroom,3).
go(sandra,garden,3).
go(daniel,garden,2).
go(daniel,office,3).
get(sandra,milk,3).
drop(sandra,milk,4).
go(daniel,hallway,4).
