go(john,bedroom,1).
go(sandra,kitchen,1).
go(mary,hallway,1).
get(john,football,1).
go(john,hallway,2).
drop(john,football,2).
go(mary,garden,2).
go(john,kitchen,3).
go(sandra,hallway,2).
go(daniel,hallway,1).
drop(mary,milk,2).
go(mary,bathroom,3).
go(sandra,garden,3).
go(daniel,garden,2).
go(daniel,office,3).
get(sandra,milk,3).
drop(sandra,milk,4).
go(daniel,hallway,4).
get(sandra,milk,5).
go(daniel,garden,5).
go(daniel,kitchen,6).
go(daniel,bedroom,7).
go(mary,garden,4).
get(daniel,football,3).
go(mary,office,5).
go(sandra,bedroom,4).
drop(daniel,football,4).
get(daniel,football,5).
get(sandra,milk,6).
go(daniel,kitchen,8).
go(john,kitchen,4).
go(mary,hallway,6).
get(mary,apple,1).
drop(mary,apple,2).
go(daniel,garden,9).
go(mary,office,7).
get(john,football,6).
go(mary,kitchen,8).
get(daniel,milk,7).
go(john,bedroom,5).
go(john,hallway,6).
drop(john,football,7).
drop(daniel,milk,8).
get(john,football,8).
go(mary,garden,9).
go(daniel,bathroom,10).
go(sandra,bathroom,5).
go(mary,bathroom,10).
get(mary,apple,3).
drop(mary,apple,4).
go(daniel,office,11).
get(john,football,9).
drop(john,football,10).
go(john,garden,7).
go(daniel,garden,12).
go(sandra,garden,6).
go(daniel,kitchen,13).
go(daniel,office,14).
get(mary,milk,9).
go(daniel,bedroom,15).
go(john,office,8).
go(daniel,bathroom,16).
go(john,kitchen,9).
go(mary,garden,11).
drop(mary,milk,10).
go(john,garden,10).
get(sandra,milk,11).
drop(sandra,milk,12).
go(mary,bathroom,12).
go(mary,bedroom,13).
get(john,milk,13).
go(daniel,office,17).
go(daniel,kitchen,18).
get(daniel,apple,5).
drop(daniel,apple,6).
get(john,milk,14).
go(daniel,hallway,19).
go(mary,kitchen,14).
go(mary,office,15).
get(daniel,football,11).
go(mary,hallway,16).
go(sandra,bedroom,7).
go(mary,bedroom,17).
get(john,milk,15).
drop(john,milk,16).
go(daniel,bathroom,20).
go(sandra,bathroom,8).
get(john,milk,17).
get(mary,apple,7).
go(john,bedroom,11).
go(mary,office,18).
drop(daniel,football,12).
go(john,kitchen,12).
get(sandra,football,13).
go(john,hallway,13).
drop(sandra,football,14).
get(john,milk,18).
go(mary,hallway,19).
go(john,bedroom,14).
go(daniel,kitchen,21).
get(john,football,15).
go(mary,hallway,20).
get(john,milk,19).
go(john,kitchen,15).
go(mary,kitchen,21).
go(sandra,office,9).
go(daniel,bathroom,22).
get(daniel,apple,8).
go(sandra,garden,10).
drop(daniel,apple,9).
go(sandra,office,11).
go(daniel,kitchen,23).
drop(john,milk,20).
go(daniel,bedroom,24).
go(daniel,office,25).
go(daniel,bedroom,26).
go(mary,kitchen,22).
get(mary,football,16).
go(daniel,hallway,27).
go(john,bedroom,16).
get(daniel,apple,10).
go(sandra,garden,12).
go(daniel,garden,28).
drop(daniel,apple,11).
go(mary,bedroom,23).
go(john,hallway,17).
go(john,bedroom,18).
get(sandra,apple,12).
go(john,kitchen,19).
go(mary,bathroom,24).
go(mary,garden,25).
go(sandra,kitchen,13).
drop(sandra,apple,13).
go(mary,bedroom,26).
go(mary,kitchen,27).
go(john,office,20).
go(mary,hallway,28).
go(daniel,bedroom,29).
go(mary,bathroom,29).
go(sandra,hallway,14).
get(sandra,milk,21).
go(mary,office,30).
go(mary,hallway,31).
go(daniel,bathroom,30).
go(sandra,office,15).
go(john,garden,21).
go(sandra,hallway,16).
go(daniel,office,31).
go(mary,office,32).
go(john,kitchen,22).
go(sandra,bedroom,17).
go(sandra,office,18).
go(daniel,kitchen,32).
get(john,football,17).
go(sandra,bedroom,19).
go(sandra,hallway,20).
get(john,football,18).
go(daniel,bathroom,33).
go(sandra,bedroom,21).
go(mary,kitchen,33).
get(john,football,19).
drop(sandra,milk,22).
go(john,garden,23).
go(daniel,hallway,34).
go(mary,kitchen,34).
get(john,milk,23).
drop(john,milk,24).
get(john,milk,25).
go(mary,garden,35).
go(john,bedroom,24).
get(mary,football,20).
go(john,office,25).
go(mary,bedroom,36).
go(john,bedroom,26).
go(john,bathroom,27).
go(mary,bathroom,37).
go(mary,kitchen,38).
go(mary,office,39).
go(sandra,kitchen,22).
get(daniel,apple,14).
go(sandra,garden,23).
go(mary,bedroom,40).
go(daniel,kitchen,35).
drop(mary,football,21).
go(john,bathroom,28).
go(john,hallway,29).
get(mary,milk,26).
go(mary,bedroom,41).
get(sandra,football,22).
go(sandra,office,24).
go(sandra,bathroom,25).
go(john,bedroom,30).
go(john,bathroom,31).
drop(sandra,football,23).
drop(mary,milk,27).
go(sandra,kitchen,26).
get(daniel,milk,28).
go(john,garden,32).
go(daniel,hallway,36).
go(daniel,bathroom,37).
drop(daniel,milk,29).
get(daniel,milk,30).
get(john,apple,15).
go(sandra,kitchen,27).
go(john,hallway,33).
go(sandra,garden,28).
go(daniel,kitchen,38).
go(sandra,bedroom,29).
go(daniel,hallway,39).
go(sandra,kitchen,30).
go(sandra,bathroom,31).
go(john,kitchen,34).
get(sandra,football,24).
go(sandra,kitchen,32).
drop(sandra,football,25).
get(sandra,football,26).
drop(sandra,football,27).
go(john,bathroom,35).
go(daniel,kitchen,40).
go(john,kitchen,36).
go(daniel,hallway,41).
go(sandra,kitchen,33).
go(mary,office,42).
go(daniel,office,42).
go(sandra,bathroom,34).
get(john,milk,31).
get(john,apple,16).
go(sandra,office,35).
go(mary,hallway,43).
go(john,bathroom,37).
drop(john,apple,17).
drop(john,milk,32).
get(john,apple,18).
go(daniel,bathroom,43).
get(john,milk,33).
go(daniel,garden,44).
go(sandra,bathroom,36).
go(john,kitchen,38).
go(mary,office,44).
go(mary,hallway,45).
go(john,bedroom,39).
go(daniel,office,45).
go(daniel,bedroom,46).
get(john,milk,34).
go(john,garden,40).
go(sandra,office,37).
go(daniel,office,47).
go(john,kitchen,41).
go(mary,garden,46).
get(john,football,28).
drop(john,football,29).
drop(john,milk,35).
go(daniel,kitchen,48).
go(mary,bathroom,47).
go(daniel,office,49).
go(daniel,hallway,50).
go(daniel,garden,51).
go(mary,kitchen,48).
go(daniel,office,52).
go(mary,bathroom,49).
go(john,hallway,42).
get(daniel,football,30).
go(daniel,kitchen,53).
drop(daniel,football,31).
go(john,bathroom,43).
get(daniel,football,32).
go(john,kitchen,44).
go(mary,office,50).
go(john,hallway,45).
go(john,office,46).
go(daniel,bedroom,54).
get(daniel,milk,36).
drop(daniel,milk,37).
go(sandra,bathroom,38).
go(mary,bedroom,51).
get(daniel,apple,19).
drop(daniel,football,33).
go(sandra,garden,39).
get(daniel,apple,20).
drop(daniel,apple,21).
go(sandra,office,40).
go(john,kitchen,47).
go(sandra,garden,41).
go(daniel,bathroom,55).
go(mary,hallway,52).
go(sandra,bathroom,42).
go(john,bedroom,48).
go(mary,garden,53).
get(john,apple,22).
go(john,kitchen,49).
go(john,garden,50).
go(mary,office,54).
go(daniel,bedroom,56).
go(john,bathroom,51).
drop(john,apple,23).
go(mary,bedroom,55).
get(sandra,apple,24).
go(daniel,kitchen,57).
get(john,apple,25).
go(sandra,kitchen,43).
go(sandra,bathroom,44).
go(daniel,office,58).
drop(john,apple,26).
go(mary,kitchen,56).
go(sandra,garden,45).
go(sandra,bathroom,46).
go(daniel,garden,59).
get(sandra,apple,27).
go(mary,bedroom,57).
go(john,hallway,52).
go(sandra,office,47).
get(mary,milk,38).
go(john,kitchen,53).
go(mary,hallway,58).
drop(sandra,apple,28).
get(mary,milk,39).
get(john,football,34).
go(john,hallway,54).
