go(john,bedroom,1).
go(sandra,kitchen,1).
go(mary,hallway,1).
get(john,football,1).
go(john,hallway,2).
drop(john,football,2).
go(mary,garden,2).
go(john,kitchen,3).
go(sandra,hallway,2).
go(daniel,hallway,1).
drop(mary,milk,2).
go(mary,bathroom,3).
go(sandra,garden,3).
go(daniel,garden,2).
go(daniel,office,3).
get(sandra,milk,3).
drop(sandra,milk,4).
go(daniel,hallway,4).
get(sandra,milk,5).
go(daniel,garden,5).
go(daniel,kitchen,6).
go(daniel,bedroom,7).
go(mary,garden,4).
get(daniel,football,3).
go(mary,office,5).
go(sandra,bedroom,4).
drop(daniel,football,4).
get(daniel,football,5).
get(sandra,milk,6).
go(daniel,kitchen,8).
go(john,kitchen,4).
go(mary,hallway,6).
get(mary,apple,1).
drop(mary,apple,2).
