go(john,bedroom,1).
go(sandra,kitchen,1).
go(mary,hallway,1).
get(john,football,1).
go(john,hallway,2).
drop(john,football,2).
go(mary,garden,2).
go(john,kitchen,3).
go(sandra,hallway,2).
go(daniel,hallway,1).
drop(mary,milk,2).
go(mary,bathroom,3).
go(sandra,garden,3).
go(daniel,garden,2).
go(daniel,office,3).
get(sandra,milk,3).
drop(sandra,milk,4).
go(daniel,hallway,4).
get(sandra,milk,5).
go(daniel,garden,5).
go(daniel,kitchen,6).
go(daniel,bedroom,7).
go(mary,garden,4).
get(daniel,football,3).
go(mary,office,5).
go(sandra,bedroom,4).
drop(daniel,football,4).
get(daniel,football,5).
get(sandra,milk,6).
go(daniel,kitchen,8).
go(john,kitchen,4).
go(mary,hallway,6).
get(mary,apple,1).
drop(mary,apple,2).
go(daniel,garden,9).
go(mary,office,7).
get(john,football,6).
go(mary,kitchen,8).
get(daniel,milk,7).
go(john,bedroom,5).
go(john,hallway,6).
drop(john,football,7).
drop(daniel,milk,8).
get(john,football,8).
go(mary,garden,9).
go(daniel,bathroom,10).
go(sandra,bathroom,5).
go(mary,bathroom,10).
get(mary,apple,3).
drop(mary,apple,4).
go(daniel,office,11).
get(john,football,9).
drop(john,football,10).
go(john,garden,7).
go(daniel,garden,12).
go(sandra,garden,6).
go(daniel,kitchen,13).
go(daniel,office,14).
get(mary,milk,9).
go(daniel,bedroom,15).
go(john,office,8).
go(daniel,bathroom,16).
go(john,kitchen,9).
go(mary,garden,11).
drop(mary,milk,10).
go(john,garden,10).
get(sandra,milk,11).
drop(sandra,milk,12).
go(mary,bathroom,12).
go(mary,bedroom,13).
get(john,milk,13).
go(daniel,office,17).
go(daniel,kitchen,18).
get(daniel,apple,5).
drop(daniel,apple,6).
get(john,milk,14).
go(daniel,hallway,19).
go(mary,kitchen,14).
go(mary,office,15).
get(daniel,football,11).
go(mary,hallway,16).
go(sandra,bedroom,7).
go(mary,bedroom,17).
get(john,milk,15).
drop(john,milk,16).
go(daniel,bathroom,20).
go(sandra,bathroom,8).
get(john,milk,17).
get(mary,apple,7).
go(john,bedroom,11).
go(mary,office,18).
drop(daniel,football,12).
go(john,kitchen,12).
get(sandra,football,13).
go(john,hallway,13).
drop(sandra,football,14).
get(john,milk,18).
go(mary,hallway,19).
go(john,bedroom,14).
go(daniel,kitchen,21).
get(john,football,15).
go(mary,hallway,20).
get(john,milk,19).
go(john,kitchen,15).
go(mary,kitchen,21).
go(sandra,office,9).
go(daniel,bathroom,22).
get(daniel,apple,8).
go(sandra,garden,10).
drop(daniel,apple,9).
go(sandra,office,11).
go(daniel,kitchen,23).
drop(john,milk,20).
go(daniel,bedroom,24).
go(daniel,office,25).
go(daniel,bedroom,26).
go(mary,kitchen,22).
get(mary,football,16).
go(daniel,hallway,27).
go(john,bedroom,16).
